name: Create and push Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 # reuses already existing GitHub action   
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/website_1.0 --build-arg MY_MAIL_PASSWORD=${{ secrets.MY_MAIL_PASSWORD }}
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Docker push 
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/website_1.0:latest
    
  
